# ZMQ properties
data_queue_port: 5551
controls_queue_port: 5552
# Constant properties
path_to_training: "../../training/"
recording_height: 80
recording_width: 160
recording_fps: 20
frame_height: 50
frame_width: 160

# Procedural flags
control_mode: full_model # modes: full_model, shared, full_expert

m_length: 1 # memory length
m_interval: 1 # memory interval

# Imitation learning
dagger_training_enabled: true
dagger_epoch_size: 1600
dagger_epochs_count: 12